audit/urls.py
from django.conf.urls import url, include

from audit.views import DiscrepanciesBread, VumiLogsBread


urlpatterns = [
    url(r'^sms/auditing/discrepancies/', include(DiscrepanciesBread().get_urls(prefix=False))),
    url(r'^sms/auditing/vumilogs/', include(VumiLogsBread().get_urls(prefix=False))),
]

libya_elections/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from rapidsms.backends.vumi.views import VumiBackendView

from libya_elections.admin_site import admin_site
from staff.views import gitrev_view


urlpatterns = [
    # HNEC Staff applications
    url(r'^django-admin/', include(admin_site.urls)),

    url(r'^admin/', include('libya_elections.urls_admin')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^data/', include('vr_dashboard.urls', namespace='vr_dashboard')),
    url(r'^elections/', include('libya_elections.urls_elections')),
    url(r'^gitrev/$', gitrev_view, name='gitrev'),
    url(r'^health/$', TemplateView.as_view(template_name="health.html")),
    url(r'^help_desk/', include('help_desk.urls')),
    url(r'^messages/', include('text_messages.urls')),
    url(r'^registration/', include('libya_elections.urls_registration')),
    url(r'^reporting/', include('reporting_api.urls')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sms/send/', include('bulk_sms.urls')),
    url(r'^sms/', include('libya_elections.urls_sms')),
    url(r'^staff/', include('staff.urls')),
    url(r'^voter/', include('civil_registry.urls')),

    url(r'', include('audit.urls')),
    url(r'', include('subscriptions.urls')),

    # Public web site
    url(r'', include('libya_site.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "vumi-fake-smsc" in settings.INSTALLED_BACKENDS:
    urlpatterns += [
        url(r"^backend/vumi-fake-smsc/$",
            VumiBackendView.as_view(backend_name="vumi-fake-smsc")),
    ]
if "vumi-http" in settings.INSTALLED_BACKENDS:
    urlpatterns += [
        url(r"^backend/vumi-http/$",
            VumiBackendView.as_view(backend_name="vumi-http")),
    ]
if "libyana" in settings.INSTALLED_BACKENDS:
    urlpatterns += [
        url(r"^backend/vumi-libyana/$",
            VumiBackendView.as_view(backend_name="libyana")),
    ]
if "almadar" in settings.INSTALLED_BACKENDS:
    urlpatterns += [
        url(r"^backend/vumi-almadar/$",
            VumiBackendView.as_view(backend_name="almadar")),
    ]
if "thuraya" in settings.INSTALLED_BACKENDS:
    urlpatterns += [
        url(r"^backend/vumi-thuraya/$",
            VumiBackendView.as_view(backend_name="thuraya")),
    ]

# enable our forked httptester on testing
if settings.ENVIRONMENT != 'production':
    urlpatterns += [
        url(r'^httptester/', include('httptester.urls')),
    ]

vr_dashboard/urls.py
from django.conf.urls import url

from .views.views import csv_daily_report, csv_report, election_day, election_day_center, \
    election_day_center_n, election_day_office_n, election_day_preliminary, national, offices, \
    offices_detail, redirect_to_national, regions, sms, subconstituencies, weekly, election_day_hq

from .views.phone_tool import matching_phones, phone_history, phone_message_tool, whitelist_phone

urlpatterns = (
    url(r'^$', redirect_to_national),
    url(r'^election_day/$', election_day, name='election-day'),
    url(r'^election_day/hq/$', election_day_hq, name='election-day-hq'),
    url(r'^election_day/preliminary/$', election_day_preliminary, name='election-day-preliminary'),
    url(r'^election_day/center/$', election_day_center, name='election-day-center'),
    url(r'^election_day/center/(?P<center_id>[\d]+)/$', election_day_center_n,
        name='election-day-center-n'),
    url(r'^election_day/office/(?P<office_id>[\d]+)/$', election_day_office_n,
        name='election-day-office-n'),
    url(r'^national/$', national, name='national'),
    url(r'^offices/$', offices, name='offices'),
    url(r'^offices_detail/$', offices_detail, name='offices-detail'),
    url(r'^regions/$', regions, name='regions'),
    url(r'^sms/$', sms, name='sms'),
    url(r'^subconstituencies/$', subconstituencies, name='subconstituencies'),
    url(r'^weekly/$', weekly, name='weekly'),
    url(r'^csv/$', csv_report, name='csv'),
    url(r'^daily_csv/$', csv_daily_report, name='daily-csv'),
    url(r'^phone_tool/$', phone_message_tool, name='phone-message-tool'),
    url(r'^phone_tool/matching_phones/$', matching_phones, name='search-phones'),
    url(r'^phone_tool/phone_history/$', phone_history, name='phone-history'),
    url(r'^phone_tool/whitelist_phone/$', whitelist_phone, name='whitelist-phone')
)

vr_dashboard/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from libya_elections.constants import CENTER_ID_MAX_INT_VALUE, CENTER_ID_MIN_INT_VALUE
from libya_elections.phone_numbers import PhoneNumberFormField
from register.models import RegistrationCenter


def get_invalid_center_error_string(center_id):
    """ Assumptions: This will be escaped before presenting to the user
    in case user input is provided directly.
    """
    return _("Center %s is not a valid center.") % center_id


class PhoneAndMessageQueryForm(forms.Form):
    phone_number = PhoneNumberFormField(required=False, disable_help_text=True)
    center_id = forms.IntegerField(min_value=CENTER_ID_MIN_INT_VALUE,
                                   max_value=CENTER_ID_MAX_INT_VALUE,
                                   required=False,
                                   widget=forms.TextInput)

    search_usage_message = _('Either a phone number or a center must be supplied, but not both.')

    def clean(self):
        cleaned_data = super(PhoneAndMessageQueryForm, self).clean()
        phone_number = cleaned_data.get('phone_number')
        center_id = cleaned_data.get('center_id')
        if not phone_number and not center_id:
            raise forms.ValidationError(self.search_usage_message)
        if phone_number and center_id:
            raise forms.ValidationError(self.search_usage_message)

    def clean_center_id(self):
        center_id = self.cleaned_data.get('center_id')
        if center_id and not RegistrationCenter.objects.filter(center_id=center_id).exists():
            raise forms.ValidationError(get_invalid_center_error_string(center_id))
        return center_id

vr_dashboard/views/phone_tool.py
from django.contrib.auth.decorators import user_passes_test
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseBadRequest, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.timezone import now
from django.utils.translation import ugettext as _

from libya_elections.phone_numbers import is_phone_number_valid
from polling_reports.models import StaffPhone
from register.models import RegistrationCenter, SMS, Whitelist
from register.utils import is_center_id_valid
from reporting_api.codings import MESSAGE_TYPES
from vr_dashboard.forms import get_invalid_center_error_string, PhoneAndMessageQueryForm


@user_passes_test(lambda user: user.is_staff)
def phone_message_tool(request):
    if request.method == 'POST':
        form = PhoneAndMessageQueryForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['phone_number']:
                query_args = '?phone=%s' % form.cleaned_data['phone_number']
                return HttpResponseRedirect(reverse('vr_dashboard:phone-history') + query_args)
            else:
                query_args = '?center_id=%s' % form.cleaned_data['center_id']
                return HttpResponseRedirect(reverse('vr_dashboard:search-phones') + query_args)
    else:
        form = PhoneAndMessageQueryForm()

    context = {
        'form': form,
        'phone_tool_page': True,
        'staff_page': True,
    }
    return render(request, 'vr_dashboard/phone_tool/query_form.html', context)


def get_phone_tool_error(error_class, request, error_msg):
    args = {
        'error_msg': error_msg,
        'phone_tool_page': True,
        'staff_page': True,
        'user': request.user,
        'request': request
    }
    return error_class(render_to_string('vr_dashboard/error.html', args))


def get_bogus_arg_error(request):
    return get_phone_tool_error(HttpResponseBadRequest,
                                request,
                                _('This request is not intended to be called directly.'))


def get_non_staff_phone_error(request, phone_number):
    return get_phone_tool_error(HttpResponseNotFound,
                                request,
                                _("Phone number %s is not a valid staff phone.") % phone_number)


def get_invalid_center_error(request, center_id):
    return get_phone_tool_error(HttpResponseNotFound,
                                request,
                                get_invalid_center_error_string(center_id))


def get_no_matching_phones_error(request):
    return get_phone_tool_error(HttpResponseNotFound,
                                request,
                                _('No matching phones were found.'))


@user_passes_test(lambda user: user.is_staff)
def matching_phones(request):
    center_id = request.GET.get('center_id')
    if not center_id or not is_center_id_valid(center_id):
        return get_bogus_arg_error(request)  # user bypassed form validation

    matches = StaffPhone.objects.filter(registration_center__center_id=center_id)
    if not matches.exists():
        if not RegistrationCenter.objects.filter(center_id=center_id).exists():
            return get_invalid_center_error(request, center_id)
        else:
            return get_no_matching_phones_error(request)

    for phone in matches:
        try:
            phone.whitelist = Whitelist.objects.get(phone_number=phone.phone_number)
        except Whitelist.DoesNotExist:
            pass

    return render(request, 'vr_dashboard/phone_tool/phone_list.html', {
        'phone_tool_page': True,
        'staff_page': True,
        'phones': matches,
        'center_id': center_id,
    })


@user_passes_test(lambda user: user.is_staff)
def phone_history(request):
    if 'phone' not in request.GET:
        return get_bogus_arg_error(request)

    phone_number = request.GET['phone']
    if not is_phone_number_valid(phone_number):
        return get_bogus_arg_error(request)  # user bypassed form validation

    try:
        staff_phone = StaffPhone.objects.get(phone_number=phone_number)
    except StaffPhone.DoesNotExist:
        # This feature is only for staff phones, but we need to be able to
        # find messages from would-be staff phones that haven't been
        # successfully linked.
        staff_phone = None

    try:
        whitelist = Whitelist.objects.get(phone_number=phone_number)
    except Whitelist.DoesNotExist:
        whitelist = None

    either_number = Q(from_number=phone_number) | Q(to_number=phone_number)
    sms_messages = SMS.objects.filter(either_number).order_by('-creation_date')
    for message in sms_messages:
        message.msg_type_string = MESSAGE_TYPES.get(message.msg_type, message.msg_type)

    return render(request, 'vr_dashboard/phone_tool/message_list.html', {
        'phone_tool_page': True,
        'staff_page': True,
        'sms_messages': sms_messages,
        'whitelist': whitelist,
        'phone': staff_phone,
        'phone_number': phone_number  # whether or not it is a staff phone
    })


@user_passes_test(lambda user: user.is_staff)
def whitelist_phone(request):
    phone_number = request.POST.get('phone')
    if not phone_number or not is_phone_number_valid(phone_number):
        return get_bogus_arg_error(request)  # user bypassed form validation

    center_id = request.POST.get('center_id')
    if center_id:
        if not is_center_id_valid(center_id):
            return get_bogus_arg_error(request)  # user bypassed form validation

    white_list = Whitelist(creation_date=now(), modification_date=now(), phone_number=phone_number)
    white_list.full_clean()
    white_list.save()

    # refresh the page that sent us here, now with the phone white-listed
    if center_id:
        query_args = '?center_id=%s' % center_id
        return HttpResponseRedirect(reverse('vr_dashboard:search-phones') + query_args)
    else:
        query_args = '?phone=%s' % phone_number
        return HttpResponseRedirect(reverse('vr_dashboard:phone-history') + query_args)

vr_dashboard/templates/vr_dashboard/base.html
{% extends "libya_site/base.html" %}
{% load i18n staticfiles %}

{% block extra_css %}
  <link href="{% static 'css/charts.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}{% trans "Registration Statistics" %}{% endblock %}

{% block subnav %}
{% endblock %}

{% block status_messages %}
<div id="status-messages" class="page-width cushion">

	<div class="table-layout">
		<div>
		  <div class="kumquat">
            <img src="{% static 'img/summary.png' %}" height="80" class="centered">
          </div>
		  <div class="milk cushion">
            <label>{% trans 'Summary' %}</label>
			<p>{{ headline_stats }}</p>
		  </div>
		</div>
	</div>

	<div class="spacer"></div>

	<div class="table-layout">
	  <div>
		<div class="kumquat">
		  <img class="centered" src="{% static 'img/registration.png' %}" height="80">
		</div>
		<div class="milk cushion">
          <label>{% trans 'Registration' %}</label>
		  <p><a href="{% url 'check_registration' %}">
            <strong>{% trans "Check your registration information" %}</strong>
          </a></p>
		</div>
	  </div>
	</div>

	<div class="clear spacer"></div>

</div>
{% endblock status_messages %}

{% block charts %}
<nav class="page-width cushion-sides tabs">
	<a {% if national_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:national' %}">{% trans "Libya" %}</a>
	<a {% if regions_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:regions' %}">{% trans "Regions" %}</a>
	<a {% if offices_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:offices' %}">{% trans "Offices" %}</a>
    {% if user.is_staff %}
        <a {% if offices_detail_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:offices-detail' %}">
            {% trans "Offices Detail" %}
        </a>
        <a {% if subconstituencies_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:subconstituencies' %}">
            {% trans "Subconstituencies" %}
        </a>
        <a {% if weekly_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:weekly' %}">{% trans "Weekly" %}</a>
        <a {% if sms_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:sms' %}">{% trans "SMS" %}</a>
    {% endif %}
</nav>
<div class="plum" style="overflow:auto">
	<div class="float-layout page-width">

		{% if new_reg_chart or cum_reg_chart %}

      <div id="slider-container" class="full">
        <div class="cushion">
          <label class="text-centered block" for="slider">{% trans "Period:" %} <span id="start_date"></span> - <span id="end_date"></span></label>
          <input id="slider" type="range" style="width:100%">
        </div>
      </div>

			{% if new_reg_chart %}
				<div class="chart-container half">
					<div class="cushion">
						<h2>{% trans "New Registrations" %}</h2>
						<div class="milk">
							<div id="left-chart-container-inner" class="chart-container-inner">
								<div id="new-registrations-chart" class="chart">
									<svg style="height: 200px"></svg>
								</div>
							</div>
						</div>
					</div>
				</div>
			{% endif %}

			{% if cum_reg_chart %}
				<div class="chart-container half">
					<div class="cushion">
						<h2>{% trans "Cumulative Registrations" %}</h2>
						<div class="milk">
							<div id="right-chart-container-inner" class="chart-container-inner">
								<div id="cumulative-registrations-chart" class="chart">
									<svg style="height: 200px"></svg>
								</div>
							</div>
						</div>
					</div>
				</div>
			{% endif %}

			{% block right_chart %}{% endblock %}

		{% endif %}

    </div></div>
{% endblock %}

{% block page_footer %}
  {% if user.is_staff %}
    <div class="plum">
      <div class="page-width cushion-ends">
        <label class="cushion-sides">{% trans "Last Updated: " %}{{ last_updated|date:"H:i d-m-Y"}}</label>
        <div class="right">
          <a class="button transparent" href="{% url 'vr_dashboard:csv' %}">{% trans "Download Full CSV" %}</a>
          <a class="button transparent" href="{% url 'vr_dashboard:daily-csv' %}">{% trans "Download Daily CSV" %}</a>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block extra_js %}
  {# VR Dashboard charts #}
  {% if new_reg_chart or cum_reg_chart %}
    <script>
     // provide these translations to the JavaScript charting logic
     var dashboardTrans = {
         'months': [
             '{% trans "January" %}', '{% trans "February" %}', '{% trans "March" %}',
             '{% trans "April" %}', '{% trans "May" %}', '{% trans "June" %}',
             '{% trans "July" %}', '{% trans "August" %}', '{% trans "September" %}',
             '{% trans "October" %}', '{% trans "November" %}', '{% trans "December" %}'
         ],
         'Gender': '{% trans "Gender" %}',
         'New Registrations': '{% trans "New Registrations" %}',
         'Total Registrations': '{% trans "Total Registrations" %}'
     };
    </script>
    <script src="{% static 'js/d3.js' %}" charset="utf-8"></script>
    <script src="{% static 'js/nv.d3.js' %}"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
  {% endif %}
{% endblock %}

vr_dashboard/templates/vr_dashboard/election_day_center_n.html
{% extends 'vr_dashboard/polling_base.html' %}
{% load i18n libya_tags %}
{% block content %}
  <div class="banana cushion-ends">
    <div class="page-width float-layout notice">
      <div class="third cushion">
        <h3>{% trans "Polling Center" %} {{ center_id }} - {{ center.name }}</h3>

        <p>
          <a href='{% url 'vr_dashboard:election-day-office-n' center.office_id %}'>
            {% trans "Return to Office" %} {{ center.office_id }}
          </a>
        </p>

        <br style="line-height: 40%;" />

        {% if center.copy_of_polling_center %}
          <ul>
            <li>{% trans "Copy of center" %}</li>
            <li><a href='{% url 'vr_dashboard:election-day-center-n' center.copy_of_polling_center %}'>
              {{ center.copy_of_polling_center }}</a></li>
          </ul>
        {% endif %}
        {% if copies %}
          <p>{% trans "Copies of this center:" %}</p>
          <ul>
            {% for copy in copies %}
              <li><a href='{% url 'vr_dashboard:election-day-center-n' copy %}'>{{ copy }}</a></li>
            {% endfor %}
          </ul>
        {% endif %}
        {% if center.inactive_for_election %}
          <p><strong>{% trans 'The center was inactive for this election.' %}</strong></p>
        {% endif %}

        <br />
        <h3>{% trans "Reporting" %}</h3>
        <ul>
          <li>
            {% trans "Last Opened" %}:
            {{ stats.last_opened }}
          </li>
          <li>
            {% trans "Last Reported" %}:
            {{ stats.last_report }}
          </li>
        </ul>
      </div>

      <div class="third cushion">
        <h3>{% trans "Reported Votes" %}</h3>
        <ul>
          {% if stats.reported_period_1 or stats.reported_period_2 or stats.reported_period_3 or stats.reported_period_4 %}
            {% if stats.reported_period_1 %}
              <li>
                {% trans "Reported Period" %} 1:
                {{ stats.reported_period_1|safe }}
              </li>
            {% endif %}
            {% if stats.reported_period_2 %}
              <li>
                {% trans "Reported Period" %} 2:
                {{ stats.reported_period_2|safe }}
              </li>
            {% endif %}
            {% if stats.reported_period_3 %}
              <li>
                {% trans "Reported Period" %} 3:
                {{ stats.reported_period_3|safe }}
              </li>
            {% endif %}
            {% if stats.reported_period_4 %}
              <li>
                {% trans "Reported Period" %} 4:
                {{ stats.reported_period_4|safe }}
              </li>
            {% endif %}
          {% else %}
            <li>{% trans "Not Reported" %}</li>
          {% endif %}
        </ul>

        <br />
        <h3>{% trans "Total Registrations" %}</h3>
        <ul>
          <li>
            {% trans "Total Registrations" %}:
            {{ stats.total|safe }}
          </li>
        </ul>
      </div>

      <div class="third cushion">
        <h3>{% trans "Staff Phones" %}</h3>
        <ul id='phones'>
          {% for phone in phones %}
            <li>{{ phone.number|format_phone_number }} {{ phone.timestamp }}
              <strong>{{ phone.error }}</strong>
            </li>
          {% endfor %}
        </ul>
      </div>

      <div class="clear"></div>
    </div>
  </div>

  <section class="milk">
    <div class="page-width cushion">
      {% if log %}
        <table>
          <thead>
          <tr>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Phone" %}</th>
            <th>{% trans "Message Type" %}</th>
            <th>{% trans "Reported Period" %}</th>
            <th>{% trans "Reported Votes" %}</th>
          </tr>
          </thead>
          <tbody>
          {% for message in log %}
            <tr>
              <td>{{ message.formatted_creation_date }}</td>
              <td class="phone">{{ message.phone_number|format_phone_number }}</td>
              <td>{{ message.type }}</td>
              <td>{{ message.period }}</td>
              <td>{{ message.votes }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>{% trans "No messages were received." %}</p>
      {% endif %}
    </div>
  </section>
{% endblock content %}

{% block page_footer_csv_links %}
{% endblock %}

vr_dashboard/templates/vr_dashboard/election_day_office_n.html
{% extends 'vr_dashboard/polling_base.html' %}
{% load humanize i18n %}
{% block content %}
  <div class="banana cushion-ends">
    <div class="page-width float-layout notice">

      <div class="third cushion">
        <h3>{% trans "Office" %} {{ office_id }} - {{ office_name }}</h3>

        <p>
          <a href='{% url 'vr_dashboard:election-day' %}'>
            {% trans "Return to Overview" %}
          </a>
        </p>
      </div>

      <div class="third cushion">
        <p><em>{{ headline.as_of_datetime }}</em></p>
        <ul>
          <li>{{ headline.open_centers|safe }}</li>
          <li>{{ headline.unopen_centers|safe }}</li>
        </ul>
      </div>

      <div class="third cushion">
        <ul>
          <li>{{ headline.period1|safe }}</li>
          <li>{{ headline.period2|safe }}</li>
          <li>{{ headline.period3|safe }}</li>
          <li>{{ headline.period4|safe }}</li>
        </ul>
      </div>

      <div class="clear"></div>
    </div>
  </div>

  <section class="milk">
    <div class="page-width cushion">
      <table class='centers_table'>
        <thead>
        <tr>
          <th>{% trans "Polling Center" %}</th>
          <th>{% trans "Code" %}</th>
          <th>{% trans "Opened" %}</th>
          <th>{% trans "Reported Period" %} 1</th>
          <th>{% trans "Reported Period" %} 2</th>
          <th>{% trans "Reported Period" %} 3</th>
          <th>{% trans "Reported Period" %} 4</th>
        </tr>
        </thead>
        <tbody>
        {% for row in office_centers_table %}
          <tr {% if row.tr_class %}class="{{ row.tr_class }}"{% endif %}>
            <td>
              <a href='{% url 'vr_dashboard:election-day-center-n' row.polling_center_code %}'>{{ row.name }}</a>
            </td>
            <td>{{ row.polling_center_code }}</td>
            {% if row.opened_today %}
              <td>{{ row.opened_today }}</td>{% elif row.inactive_for_election %}
              <td class="inactive-center-flag">{% trans "Inactive" %}</td>{% else %}
              <td>-</td>{% endif %}
            <td class="{{ row.reported_period_1 }}">{{ row.reported_period_1_printable }}</td>
            <td class="{{ row.reported_period_2 }}">{{ row.reported_period_2_printable }}</td>
            <td class="{{ row.reported_period_3 }}">{{ row.reported_period_3_printable }}</td>
            <td class="{{ row.reported_period_4 }}">{{ row.reported_period_4_printable }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
{% endblock content %}

vr_dashboard/templates/vr_dashboard/error.html
{% extends 'vr_dashboard/base.html' %}
{% block content %}
{% include 'vr_dashboard/includes/error_core.html' %}
{% endblock %}

vr_dashboard/templates/vr_dashboard/phone_tool_base.html
{% extends "libya_site/staff.html" %}
{% load i18n staticfiles %}

{% block title %}{% trans "Phone and Message Tool" %}{% endblock %}
{% block charts %}
  <div class="page-width cushion-ends">

    <h1 class="left">{% trans "Phone and Message Tool" %}</h1>


    <div class="clear"></div>
  </div>

{% endblock %}

{% block content %}
  {% block main_content %}
  {% endblock %}

  {% block bottom_buttons %}
    <div class="page-width cushion">
      {% if not form %}
        <a href="{% url 'vr_dashboard:phone-message-tool' %}">
          <button type="submit">{% trans "Enter Another Phone or Center ID #" %}</button>
        </a>
      {% endif %}
      <a class="right" href="{% url 'vr_dashboard:election-day' %}">
        <button type="submit" class="inverse">{% trans "Return to Polling Centers Monitoring" %}</button>
      </a>
    </div>
  {% endblock bottom_buttons %}
{% endblock %}

vr_dashboard/templates/vr_dashboard/polling_base.html
{% extends "libya_site/staff.html" %}
{% load i18n staticfiles %}

{% block title %}{% trans "Polling Center Monitoring" %}{% endblock %}

{% block charts %}
  <div class="page-width cushion-ends">

    <h1 class="left">{% trans "Polling Center Monitoring" %}</h1>

    <a href="{% url 'vr_dashboard:phone-message-tool' %}" class="right">
      <button type="submit">{% trans "Phone Tool" %}</button>
    </a>
    <div class="clear"></div>

    {% if selected_election %}
      <form>
        <label class="inline" for="select-election">{% trans "Election Title" %}</label>
        <select id="select-election" onchange="location = this.options[this.selectedIndex].value;">
          {% for election in elections %}
            <option value="{{ request.path }}?election={{ election.id }}"
                    {% if election.id == selected_election.id %}
                    selected
                    {% endif %}
                    >
              {{ election.name }}
            </option>
          {% endfor %}
        </select>
      </form>
    {% endif %}

    <div class="clear"></div>
  </div>

  <div class="page-width">

    <nav class="tabs">
      <a {% if election_day_overview_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:election-day' %}">
        {% trans "Overview" %}
      </a>
      <a {% if election_day_center_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:election-day-center' %}">
        {% trans "Center List" %}
      </a>
      <a {% if election_day_hq_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:election-day-hq' %}">
        {% trans "HQ" %}
      </a>
      <a {% if election_day_preliminary_votes_page %} class="selected" {% endif %} href="{% url 'vr_dashboard:election-day-preliminary' %}">
        {% trans "Preliminary Vote Counts" %}
      </a>
    </nav>
  </div>

{% endblock %}

{% block page_footer %}
  <div class="milk">
    <div class="page-width cushion-ends">
      <label class="cushion-sides">{% trans "Last Updated: " %}{{ last_updated|date:"H:i d-m-Y"}}</label>
      {% block page_footer_csv_links %}
        <div class="right">
          <a class="button transparent" href="{{ request.path }}?format=csv">{% trans "Download CSV" %}</a>
        </div>
      {% endblock %}
    </div>
  </div>
{% endblock %}

vr_dashboard/templates/vr_dashboard/polling_error.html
{% extends 'vr_dashboard/polling_base.html' %}
{% block content %}
{% include 'vr_dashboard/includes/error_core.html' %}
{% endblock %}